// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.
// Active brand: fengchihermes. Run `pnpm brand:sync` (BRAND=<id>) to regenerate.

export interface BrandConfig {
  id: string;
  appName: string;
  appNameEn: string;
  productName: string;
  identifier: string;
  dataDirName: string;
  providerKey: string;
  serviceUrl: string;
  rechargeUrl: string;
  copyright: string;
  publisher: string;
  homepage: string;
  shortDescription: string;
  longDescription: string;
  tagline: string;
  edition: string;
  updateManifestUrl: string;
  updateDownloadUrl: string;
}

export const BRAND: BrandConfig = {
  "id": "fengchihermes",
  "appName": "风驰云",
  "appNameEn": "Fengchiyun",
  "productName": "FengchiHermes Desktop",
  "identifier": "app.fengchihermes.desktop",
  "dataDirName": ".fengchihermes",
  "providerKey": "fengchihermes",
  "serviceUrl": "https://ai.fengchiyun.com/",
  "rechargeUrl": "https://ai.fengchiyun.com/wallet",
  "copyright": "Copyright © 2026 FengchiHermes",
  "publisher": "FengchiHermes",
  "homepage": "https://ai.fengchiyun.com",
  "shortDescription": "FengchiHermes AI Assistant Desktop",
  "longDescription": "Desktop app for FengchiHermes AI Assistant.",
  "tagline": "AI Assistant",
  "edition": "桌面版",
  "updateManifestUrl": "https://ai.fengchiyun.com/downloads/fengchihermes/latest.json",
  "updateDownloadUrl": "https://ai.fengchiyun.com/hermes-client"
} as const;

export default BRAND;
