// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.
// Active brand: hermes. Run `pnpm brand:sync` (BRAND=<id>) to regenerate.

export interface BrandConfig {
  id: string;
  appName: string;
  productName: string;
  identifier: string;
  windowTitle: string;
  dataDirName: string;
  providerKey: string;
  serviceUrl: string;
  rechargeUrl: string;
  copyright: string;
  publisher: string;
  homepage: string;
  shortDescription: string;
  longDescription: string;
  tagline: string;
}

export const BRAND: BrandConfig = {
  "id": "hermes",
  "appName": "Hermes Agent CN",
  "productName": "Hermes Agent CN Desktop",
  "identifier": "cn.org.hermesagent.desktop",
  "windowTitle": "Hermes Agent 中文社区桌面版",
  "dataDirName": ".hermes",
  "providerKey": "hermes",
  "serviceUrl": "https://hermesagent.org.cn/",
  "rechargeUrl": "https://hermesagent.org.cn/",
  "copyright": "Copyright © 2026 Hermes Agent CN Contributors",
  "publisher": "Hermes Agent CN Contributors",
  "homepage": "https://hermesagent.org.cn",
  "shortDescription": "Hermes Agent Chinese Community Desktop",
  "longDescription": "Desktop app for Hermes Agent Chinese Community Edition.",
  "tagline": "AI Assistant"
} as const;

export default BRAND;
