// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.
// Active brand: huanxinghermes. Run `pnpm brand:sync` (BRAND=<id>) to regenerate.

export interface BrandConfig {
  id: string;
  appName: string;
  appNameEn: string;
  productName: string;
  identifier: string;
  dataDirName: string;
  providerKey: string;
  serviceUrl: string;
  registerUrl: string;
  rechargeUrl: string;
  copyright: string;
  publisher: string;
  homepage: string;
  shortDescription: string;
  longDescription: string;
  tagline: string;
  edition: string;
  updateManifestUrl: string;
  updateDownloadUrl: string;
  accountDefaultModels: readonly string[];
}

export const BRAND: BrandConfig = {
  "id": "huanxinghermes",
  "appName": "寰星Agent",
  "appNameEn": "HuanxingHermes",
  "productName": "HuanxingHermes Desktop",
  "identifier": "app.HuanxingHermes.desktop",
  "dataDirName": ".huanxinghermes",
  "providerKey": "huanxinghermes",
  "serviceUrl": "https://api.huanxing.ai/",
  "registerUrl": "https://api.huanxing.ai/sign-up",
  "rechargeUrl": "https://api.huanxing.ai/wallet",
  "copyright": "Copyright © 2026 HuanxingHermes",
  "publisher": "HuanxingHermes",
  "homepage": "https://api.huanxing.ai",
  "shortDescription": "HuanxingHermes AI Assistant Desktop",
  "longDescription": "Desktop app for HuanxingHermes AI Assistant.",
  "tagline": "AI Assistant",
  "edition": "桌面版",
  "updateManifestUrl": "https://ai.fengchiyun.com/downloads/huanxinghermes/latest.json",
  "updateDownloadUrl": "https://api.huanxing.ai/hermes-client",
  "accountDefaultModels": [
    "claude-opus-4-8",
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "gpt-5.5",
    "kimi-k2.6",
    "minimax-m3",
    "mimo-v2.5-pro",
    "glm-5.1"
  ]
} as const;

export default BRAND;
