#!/usr/bin/env node
// Build-time brand injection. Reads BRAND (default "hermes"), loads
// brands/<BRAND>.json, and rewrites the files that carry brand identity
// (tauri.conf.json, Cargo.toml) plus generates brand modules consumed by the
// frontend (web/src/lib/brand.generated.ts) and Rust (src/brand_generated.rs).
//
// Modeled on scripts/sync-desktop-version.mjs — same updateJson/updateText/
// replaceOrThrow helpers and the same --check mode used by `brand:check`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

const REQUIRED_FIELDS = [
  "id",
  "appName",
  "productName",
  "identifier",
  "windowTitle",
  "dataDirName",
  "providerKey",
  "serviceUrl",
  "rechargeUrl",
  "copyright",
  "publisher",
  "homepage",
  "shortDescription",
  "longDescription",
  "tagline",
];

function pathOf(relativePath) {
  return resolve(repoRoot, relativePath);
}

function readText(relativePath) {
  return readFileSync(pathOf(relativePath), "utf8");
}

function writeText(relativePath, content) {
  writeFileSync(pathOf(relativePath), content);
}

function readJson(relativePath) {
  return JSON.parse(readText(relativePath));
}

function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function requireBrand() {
  const brandId = (process.env.BRAND || "hermes").trim();
  if (!/^[a-z][a-z0-9-]*$/.test(brandId)) {
    throw new Error(`Invalid BRAND id: ${JSON.stringify(brandId)} (expected lowercase kebab)`);
  }
  let brand;
  try {
    brand = readJson(`brands/${brandId}.json`);
  } catch {
    throw new Error(`Cannot read brands/${brandId}.json — is BRAND=${brandId} a known brand?`);
  }
  const missing = REQUIRED_FIELDS.filter((f) => typeof brand[f] !== "string" || brand[f].length === 0);
  if (missing.length > 0) {
    throw new Error(`brands/${brandId}.json missing required string fields: ${missing.join(", ")}`);
  }
  if (brand.id !== brandId) {
    throw new Error(`brands/${brandId}.json has id="${brand.id}" but filename implies "${brandId}"`);
  }
  return brand;
}

const brand = requireBrand();
const changed = [];

function updateText(relativePath, updater) {
  const before = readText(relativePath);
  const after = updater(before);
  if (after === before) return;
  changed.push(relativePath);
  if (!checkOnly) writeText(relativePath, after);
}

// Like updateText but for files this script *generates* — they may not exist
// yet on a fresh checkout, so a missing file counts as "needs writing" rather
// than an error.
function writeGenerated(relativePath, content) {
  let before = null;
  try {
    before = readText(relativePath);
  } catch (err) {
    if (err?.code !== "ENOENT") throw err;
  }
  if (before === content) return;
  changed.push(relativePath);
  if (!checkOnly) writeText(relativePath, content);
}

function updateJson(relativePath, updater) {
  const value = readJson(relativePath);
  updater(value);
  updateText(relativePath, () => stableJson(value));
}

function replaceOrThrow(text, pattern, replacement, label) {
  if (!pattern.test(text)) {
    throw new Error(`Cannot find ${label}`);
  }
  pattern.lastIndex = 0;
  return text.replace(pattern, replacement);
}

// tauri.conf.json — productName, identifier, window title, bundle metadata.
updateJson("tauri.conf.json", (config) => {
  config.productName = brand.productName;
  config.identifier = brand.identifier;
  if (Array.isArray(config.app?.windows) && config.app.windows[0]) {
    config.app.windows[0].title = brand.windowTitle;
  }
  if (config.bundle) {
    config.bundle.publisher = brand.publisher;
    config.bundle.homepage = brand.homepage;
    config.bundle.copyright = brand.copyright;
    config.bundle.shortDescription = brand.shortDescription;
    config.bundle.longDescription = brand.longDescription;
  }
});

// Cargo.toml — [package].description (regex-scoped to the [package] section).
updateText("Cargo.toml", (text) => replaceOrThrow(
  text,
  /(^\[package\][\s\S]*?^description\s*=\s*)"[^"]+"/m,
  `$1"${brand.shortDescription}"`,
  "Cargo.toml [package].description",
));

// Generated frontend module — import { BRAND } from "@/lib/brand.generated".
const tsBanner = "// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.\n"
  + `// Active brand: ${brand.id}. Run \`pnpm brand:sync\` (BRAND=<id>) to regenerate.\n`;
const tsModule = `${tsBanner}\nexport interface BrandConfig {\n`
  + REQUIRED_FIELDS.map((f) => `  ${f}: string;`).join("\n")
  + `\n}\n\nexport const BRAND: BrandConfig = ${JSON.stringify(brand, null, 2)} as const;\n\nexport default BRAND;\n`;
writeGenerated("web/src/lib/brand.generated.ts", tsModule);

// Generated Rust module — `use crate::brand_generated::*;` then BRAND_* consts.
const rsBanner = "// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.\n"
  + `// Active brand: ${brand.id}. Run \`pnpm brand:sync\` (BRAND=<id>) to regenerate.\n`;
function rsConst(name, value) {
  return `pub const ${name}: &str = ${JSON.stringify(value)};`;
}
const rsModule = `${rsBanner}\n`
  + [
    rsConst("BRAND_ID", brand.id),
    rsConst("BRAND_APP_NAME", brand.appName),
    rsConst("BRAND_PROVIDER_KEY", brand.providerKey),
    rsConst("BRAND_SERVICE_URL", brand.serviceUrl),
    rsConst("BRAND_RECHARGE_URL", brand.rechargeUrl),
    rsConst("BRAND_DATA_DIR_NAME", brand.dataDirName),
  ].join("\n")
  + "\n";
writeGenerated("src/brand_generated.rs", rsModule);

if (changed.length > 0) {
  if (checkOnly) {
    console.error(`Brand "${brand.id}" is not synchronized:`);
    for (const file of changed) console.error(`- ${file}`);
    process.exit(1);
  }
  console.log(`Synchronized brand "${brand.id}":`);
  for (const file of changed) console.log(`- ${file}`);
} else {
  console.log(`Brand "${brand.id}" is already synchronized.`);
}
