// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.
// Active brand: huanxinghermes. Run `pnpm brand:sync` (BRAND=<id>) to regenerate.

pub const BRAND_ID: &str = "huanxinghermes";
pub const BRAND_APP_NAME: &str = "寰星Agent";
pub const BRAND_PROVIDER_KEY: &str = "huanxinghermes";
pub const BRAND_SERVICE_URL: &str = "https://api.huanxing.ai/";
pub const BRAND_RECHARGE_URL: &str = "https://api.huanxing.ai/wallet";
pub const BRAND_DATA_DIR_NAME: &str = ".huanxinghermes";
pub const BRAND_WINDOW_TITLE: &str = "寰星Agent 桌面版";
pub const BRAND_UPDATE_MANIFEST_URL: &str = "https://ai.fengchiyun.com/downloads/huanxinghermes/latest.json";
