// AUTO-GENERATED by scripts/sync-brand.mjs — do not edit by hand.
// Active brand: hermes. Run `pnpm brand:sync` (BRAND=<id>) to regenerate.

pub const BRAND_ID: &str = "hermes";
pub const BRAND_APP_NAME: &str = "Hermes Agent CN";
pub const BRAND_PROVIDER_KEY: &str = "hermes";
pub const BRAND_SERVICE_URL: &str = "https://hermesagent.org.cn/";
pub const BRAND_RECHARGE_URL: &str = "https://hermesagent.org.cn/";
pub const BRAND_DATA_DIR_NAME: &str = ".hermes";
