// AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
// Active brand: ccworkhermes. Run `pnpm brand:sync` with BRAND=<id> to regenerate.

pub const BRAND_ID: &str = "ccworkhermes";
pub const BRAND_ACCOUNT_BACKEND: &str = "ccwork";
pub const BRAND_APP_NAME: &str = "ccworkhermes";
pub const BRAND_APP_NAME_EN: &str = "ccworkhermes";
pub const BRAND_PRODUCT_NAME: &str = "ccworkhermes Desktop";
pub const BRAND_PROVIDER_KEY: &str = "ccworkhermes";
pub const BRAND_SERVICE_URL: &str = "https://ccwork.site/";
pub const BRAND_TEAM_SERVICE_URL: &str = "https://ccwork.site";
pub const BRAND_REGISTER_URL: &str = "https://ccwork.site/";
pub const BRAND_RECHARGE_URL: &str = "https://ccwork.site/";
pub const BRAND_DATA_DIR_NAME: &str = ".ccworkhermes";
pub const BRAND_WINDOW_TITLE: &str = "ccworkhermes 桌面版";
pub const BRAND_HOMEPAGE: &str = "https://ccwork.site/";
pub const BRAND_UPDATE_MANIFEST_URL: &str = "https://ccwork.site/hermes/latest.json";
pub const BRAND_UPDATE_DOWNLOAD_URL: &str = "https://ccwork.site/";
pub const BRAND_ACCOUNT_DEFAULT_MODELS: &[&str] = &[];
