pub mod commands;
pub mod cron_runs;
pub mod env_file;
pub mod environment;
pub mod error;
pub mod prevent_sleep;
pub mod process;
pub mod session_archive;
pub mod session_log;
pub mod state;
pub mod tray;
pub mod ui_store;
pub mod update_stage;
pub mod util;

// Generated by `scripts/sync-brand.mjs` (run via `pnpm brand:sync`). Holds the
// active white-label brand's constants (BRAND_APP_NAME, BRAND_PROVIDER_KEY,
// BRAND_SERVICE_URL, …). Committed with the default `hermes` brand so a fresh
// checkout compiles without first running the Node sync step.
pub mod brand_generated;
